name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: Generate docs
        run: |
          bash -ex scripts/docs.sh
          touch docs/_build/html/.nojekyll

      - name: Publish docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
        if: github.ref == 'refs/heads/main'
